stages:
  - build
  - deploy

variables:
  APP_ENV: production
  DEPLOY_USER: deploy
  DEPLOY_HOST: $SERVER_IP
  SSH_PORT: $SSH_PORT
  IMAGE_NAME: "registry.gitlab.com/globens/globens-front"

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
  only:
    - master

deploy:
  stage: deploy
  image: alpine:latest
  dependencies:
    - build
  before_script:
    - apk add --no-cache openssh-client rsync coreutils bash
    - echo "$SSH_PRIVATE_KEY" | base64 -d > id_rsa
    - chmod 600 id_rsa
    - eval $(ssh-agent -s)
    - ssh-add id_rsa
    - mkdir -p ~/.ssh
    - export SSH_PORT=${SSH_PORT#PORT_}
    - ssh-keyscan -p $SSH_PORT $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - ssh -p $SSH_PORT $DEPLOY_USER@$DEPLOY_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY && docker pull $IMAGE_NAME"
    - |
      ssh -p $SSH_PORT $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
        docker stop globens_front || true
        docker rm globens_front || true
        docker run -d \
          --name globens_front \
          -p 3000:3000 \
          -e NODE_ENV=production \
          registry.gitlab.com/globens/globens-front
      EOF
  only:
    - master
